require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/undev'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'airbrake/capistrano3'
